export const GET_USERS = "ADD_USERS";
export const SORT_BY_NAME_ASCENDING = "SORT_BY_NAME_ASCENDING";
export const SORT_BY_NAME_DESCENDING = "SORT_BY_NAME_DESCENDING";
export const SORT_BY_ZIP_ASCENDING = "SORT_BY_ZIP_ASCENDING";
export const SORT_BY_ZIP_DESCCENDING = "SORT_BY_ZIP_DESCCENDING";
